version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 34123412
      POSTGRES_DB: pizzeria_db
    ports:
      - "5432:5432"
